global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'kamiikun33@gmail.com'
    from: 'makibyet101@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'makibyet101@gmail.com'
    auth_identity: 'makibyet101@gmail.com'
    auth_password: 'wthmctuygtniahfs'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
