---
- hosts: all
  become: yes
  tasks:
  - name: Installing Basic Programs
    ansible.builtin.apt:
      pkg:
      - wireguard-tools
      - rsyslog
      - logrotate
      - resolvconf
      - net-tools
