---
- hosts: all
  become: yes
  tasks:
    #  - name: Remove the 9100 from 10.10.0.0/24 iptables rule
    #    command: /usr/sbin/iptables -D TCP -s 10.10.0.0/24 -p tcp -m tcp --dport 9100 -j ACCEPT

  - name: Append the 9100 from 10.10.0.200/32 iptables rule
    command: /usr/sbin/iptables -A TCP -s 10.10.0.200/32 -p tcp -m tcp --dport 9100 -j ACCEPT
