---
- hosts: all
  become: yes
  tasks:
  - name: Run apt update
    ansible.builtin.apt:
      update_cache: yes
      
  - name: Run apt upgrade
    ansible.builtin.apt:
      name: "*"
      state: latest
